### ISSUE TITLE
add official languages

### ISSUE THREAD

**Issue by ewheeler** [datasets/country-codes#15]

**Comment by ppKrauss** [comment]
Perhaps need a rule: when exists, a list of "official languages";  "langs of official statistics" otherwise. 

As it is official information, perhaps can cut the "first ~90% more used"... Example, using the [@hanteng good link](http://www.unicode.org/cldr/charts/latest/supplemental/territory_language_information.html): Afghanistan close the 90% with {fa,ps,haz} in this order; Canada with {en,fr}...  Only set of languages with high confidence level (low margin of error), and with at least 5% of use...  

References (?): use lang list in algorithms to check terminology or words without language information (to reduce the universe to de country languages).
