### ISSUE TITLE
ISO 3166-1 numeric contains invalid values

### ISSUE THREAD

**Issue by jheeffer** [datasets/country-codes#47]
Hi, 

The values in the `ISO3166-1-numeric` column are actually [`UN M49`](http://unstats.un.org/unsd/methods/m49/m49alpha.htm) codes (which is where you scrape them from).
These two code lists overlap almost completely, except for the two top ones. Channel Islands and Sark, are not in the ISO 3166-1 standard, but are in UN M49. So maybe it's good to either remove the top ones or change the column name & description.

**Comment by ewheeler** [comment]
Thanks @jheeffer !
Great catch. I had seen UN M49 and ISO 3166-1 described as synonymous but that's not the case.
I've updated the column and description. Since UN M49 is more-or-less a superset of ISO 3166-1, it is probably the more useful version to include (until I find a reliable source to scrape ISO 3166-1 so that it can also be included)
Thanks again!

**Comment by hozn** [comment]
... But now the CSV can't be loaded, since the CSV column name wasn't updated ...
